openapi: 3.0.2
info:
  version: 1.0.0
  title: First Project
  contact:
    url: https://buildship.com
  description: This API has been created using BuildShip.
servers:
  - url: https://3rypje.buildship.run
paths:
  /action:
    post:
      x-workflow-id: yCNWbrFmOx9WCaXvsaXa
      operationId: post_action
      responses:
        default:
          description: Response Unknown
      requestBody:
        content:
          application/json:
            schema:
              description: Body of the request
              type: object
              title: Body
              properties: {}
  /checkUser:
    get:
      x-workflow-id: mCI8k8XrU7oPnpKNS4JB
      operationId: get_checkUser
      responses:
        2XX:
          description: ""
          content:
            application/json:
              schema:
                oneOf:
                  - type: object
                    properties: {}
                  - type: object
                    properties: {}
      requestBody:
        content:
          application/json:
            schema:
              description: Body of the request
              type: object
              title: Body
              properties: {}
  /createJobs:
    post:
      x-workflow-id: aH4JzEPHAxpwKVolAmE1
      operationId: post_createJobs
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: string
        "400":
          description: ""
          content:
            application/json:
              schema:
                type: string
        "404":
          description: ""
          content:
            application/json:
              schema:
                type: string
      requestBody:
        content:
          application/json:
            schema:
              description: Body of the request
              type: object
              title: Body
              properties: {}
  /chekLimit:
    get:
      x-workflow-id: NYcu63lQ8GVtB0C2xcoD
      operationId: get_chekLimit
      description: ""
      responses:
        2XX:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              description: Body of the request
              type: object
              title: Body
              properties: {}
  /info:
    post:
      x-workflow-id: 6WzXcidfUyI1MmkKSnvm
      operationId: post_info
      responses:
        2XX:
          description: ""
          content:
            application/json:
              schema:
                type: object
                properties: {}
      requestBody:
        content:
          application/json:
            schema:
              description: Body of the request
              type: object
              title: Body
              properties: {}

